Repository FSA-CS-Taurus/NaviHealth, pull requests merged in 2021-02, with the labels that each got.

#8 Redux
  package-lock.json
  package.json
  screens/Profile.js
  screens/SignIn.js
Labels: enhancement

#12 Bottom Navigation Tabs
  App.js
  assets/defaultProfile.png
  package-lock.json
  package.json
  screens/DashboardScreen.js
  screens/LoadingScreen.js
  screens/MainTabScreen.js
  screens/Profile.js
  screens/SettingScreen.js
  screens/SignIn.js
Labels: enhancement

#16 Health stats screen
  README.md
  package-lock.json
  package.json
  screens/DashboardScreen.js
  screens/HealthStatsScreen.js
  screens/MainTabScreen.js
Labels: enhancement

#29 Map tutorial
  README.md
  package-lock.json
  package.json
  screens/Map.js
Labels: enhancement

#39 feat(WelcomeScreen): added logo background and some styles
  assets/navihealthLogo2.jpg
  screens/WelcomeScreen.js
Labels: enhancement

#44 Your location
  screens/Map.js
Labels: enhancement

#47 feat(firebase): able to pull data from firebase and render onto chart
  screens/HealthStatsScreen.js
  screens/Profile.js
Labels: enhancement

#53 Updated map
  api/caloriesFunction.js
  api/firebaseMethods.js
  screens/Map.js
Labels: enhancement

#51 feat(startOrigin): updated getDirections function to update direction…
  screens/Map.js
Labels: enhancement

#54 feat(Marker) added starting point marker
  screens/Map.js
Labels: enhancement

#56 Metrics change
  api/firebaseMethods.js
  screens/HealthStatsScreen.js
  screens/Map.js
Labels: enhancement

#61 Sign in style
  api/firebaseMethods.js
  assets/bluemarker.png
  screens/Map.js
  screens/Profile.js
  screens/SignIn.js
  screens/SignUp.js
Labels: enhancement

#63 feat(weeklyStats): added toggle to view weekly stats but buggy
  App.js
  screens/HealthStatsScreen.js
  screens/HealthStatsWeeklyScreen.js
  screens/MainTabScreen.js
Labels: enhancement

#75 Health stat
  App.js
  screens/HealthStatsSample.js
  screens/HealthStatsScreen.js
  screens/HealthStatsWeeklyScreen.js
  screens/MainTabScreen.js
  screens/SignUp.js
Labels: enhancement

#76 feat(daily view): updated health stats and firebase methods to pull d…
  api/firebaseMethods.js
  screens/HealthStatsScreen.js
  screens/HealthStatsWeeklyScreen.js
  screens/MainTabScreen.js
Labels: enhancement

#85 Updated weekly health stats
  api/healthStatsMethods.js
  screens/HealthStatsScreen.js
  screens/HealthStatsWeeklyScreen.js
Labels: enhancement

#91 Edit profile
  api/firebaseMethods.js
  screens/SettingScreen.js
Labels: enhancement

#87 Combined daily and weekly health data chart into one screen with ternary
  App.js
  screens/HealthStatsSample.js
  screens/HealthStatsWeeklyScreen.js
  screens/MainTabScreen.js
  screens/Map.js
Labels: enhancement

#92 feat(added actual calories burned)
  api/firebaseMethods.js
Labels: enhancement

#95 Map Button Styling
  App.js
  screens/Map.js
Labels: enhancement

#97 feat(chart style): added stylistic elements to health stats charts
  App.js
  screens/HealthStatsMonthlyScreen.js
  screens/HealthStatsScreen.js
  screens/HealthStatsScreenDaily.js
  screens/HealthStatsScreenMain.js
  screens/HealthStatsWeeklyScreen.js
  screens/MainTabScreen.js
Labels: enhancement

#100 Changed Marker Icon & fixed your location button
  assets/redmarker.png
  screens/Map.js
Labels: enhancement

#103 feat(healthStatStyle): styled daily health stat screen
  screens/HealthStatsScreenDaily.js
  screens/HealthStatsScreenMain.js
Labels: Styling

#105 Health stat style
  screens/HealthStatsMonthlyScreen.js
  screens/HealthStatsScreenDaily.js
  screens/HealthStatsScreenMain.js
  screens/HealthStatsWeeklyScreen.js
Labels: Styling

#109 Merge updates
  api/healthStatsMethods.js
  screens/HealthStatsMonthlyScreen.js
  screens/HealthStatsScreenDaily.js
  screens/HealthStatsWeeklyScreen.js
  screens/Profile.js
  screens/ProfileStatsScreen.js
Labels: enhancement

#113 feat(bike calories calculator): added function to calculate calories …
  api/caloriesFunction.js
Labels: enhancement

#112 feat(gettingStarted screen): added screen with basic user instructions
  App.js
  screens/GetStartedScreen.js
  screens/MainTabScreen.js
  screens/SettingScreen.js
Labels: enhancement

#116 Map Button resize
  screens/Map.js
  screens/Profile.js
  screens/ProfileStatsScreen.js
Labels: enhancement

#122 Profile style
  screens/Profile.js
  screens/ProfileStatsScreen.js
Labels: Styling

#127 Fixed Map Buttons
  screens/Map.js
Labels: enhancement

#134 fixed stopNaviHandler to fix estCaloriesBurned
  api/firebaseMethods.js
Labels: bug

#136 Get started update
  screens/GetStartedScreen.js
Labels: enhancement

#144 documentation(README and cleanup): Updated README and cleaned HealthS…
  README.md
  api/caloriesFunction.js
  api/healthStatsMethods.js
  screens/GetStartedScreen.js
  screens/HealthStatsMonthlyScreen.js
  screens/HealthStatsScreenDaily.js
  screens/HealthStatsScreenMain.js
  screens/HealthStatsWeeklyScreen.js
Labels: documentation

#145 feat(README): updated README with screenshots and markdown
  README.md
  assets/mapScreenshots.jpeg
  assets/profileScreenshots.jpeg
  assets/welcomeScreenshots.jpeg
Labels: documentation

#146 doc(fixed README typo)
  README.md
Labels: documentation
